language: node_js
sudo: false
notifications:
  slack: socinfrastructure:e12hIMy47R3RWjN8Ea4eTfTr

node_js:
 - "5"
 - "4"

after_success: ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
